feat: get third party working in UI
AlaskaAirlines/auro-calendar pull request #40
Opened 2023-02-20 19:16 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #39

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-02-21 20:58 UTC, jason-capsule42 requested changes

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/demo.md
> +<auro-calendar></auro-calendar>
`This` should be in the example wrapper.

```html
<div class="exampleWrapper">
  <auro-calendar></auro-calendar>
</div>
```

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/demo.md
> +<auro-calendar forceNarrow></auro-calendar>
Let's discuss this part of the API more. I initial think the calendar should default to a single calendar and then we use an attribute to show additional month(s).

2023-02-21 20:58 UTC, jason-capsule42 commented on apiExamples/presetRange.html
> +<auro-calendar dateFrom="1677484800" dateTo="1678777200"></auro-calendar>
I want to discuss what the right `type` is for these attibutes.

I think we should be expecting a Date object and then we parse that down to what is needed for the third party library.

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/demo.md
> +<auro-calendar month="08" year="2017" min="1504216800" max="1504908000"></auro-calendar>
The examples should only use attributes necessary for the attribute(s) being explained. Is `month` and `year` necessary for `min` and `max` to work?

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/demo.md
> +<auro-calendar month="09"></auro-calendar>
Again I think we should use Date objects as much as possible. 

We can pass in a Date object to an attribute like `viewDate` and then auro-calendar can parse out the attributes that the 3rd party component needs.

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/index.html
> +    <!-- </script> -->
Commented out code needs to be removed.

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/index.html
> +    <script type="module" src="../apiExamples/weekdayHeaderNotation.js"></script> -->
Commented out code needs to be removed.

2023-02-21 20:58 UTC, jason-capsule42 commented on demo/index.html
> +    <script type="module" src="../node_modules/wc-range-datepicker/dist/src/range-datepicker-calendar.js"></script>
Is this needed? Should the script below already be importing this?

We definitely wouldn't want a user to import a 3rd party tool directly like this.

2023-02-21 20:58 UTC, jason-capsule42 commented on src/auro-calendar-month.js
> +}
This should be happening in the root folder ./index.js like we do in hyperlink.

2023-02-21 20:58 UTC, jason-capsule42 commented on src/auro-calendar-month.js
> +class AuroCalendarMonth extends RangeDatepickerCalendar {
This needs to be converted to an export like hyperlink.

2023-02-21 20:58 UTC, jason-capsule42 commented on src/auro-calendar.js
> +class AuroCalendar extends RangeDatepicker {
This needs to be an export like hyperlink.

2023-02-21 20:58 UTC, jason-capsule42 commented on src/style.scss
> +}
I would make this selector be a left margin applied to `:not(first....)`

2023-02-22 20:49 UTC, closed without merging

2023-02-22 20:50 UTC, jordanjones243 commented
Reference this ticket for further work for a Range Datepicker POV:
- https://github.com/AlaskaAirlines/auro-datepicker/issues/106